Repository JavierSegoviaCordoba/kopy, pull requests merged in 2024-08, with the labels that each got.

#20 Add `kopykat` comparison
  README.md
Labels: documentation

#25 Add Kotlin Multiplatform support
  CHANGELOG.md
  README.md
  kopy-args/build.gradle.kts
  kopy-args/main/kotlin/com/javiersc/kotlin/kopy/args/KopyFunctions.kt
  kopy-args/main/kotlin/com/javiersc/kotlin/kopy/args/KopyVisibility.kt
  kopy-args/test/kotlin/com/javiersc/kotlin/kopy/args/KopyFunctionsTest.kt
  kopy-args/test/kotlin/com/javiersc/kotlin/kopy/args/KopyVisibilityTest.kt
  kopy-runtime/build.gradle.kts
  kotlin-js-store/yarn.lock
Labels: enhancement

#28 Fix type mismatch errors inside the `copy` function are not shown
  CHANGELOG.md
  kopy-compiler/main/kotlin/com/javiersc/kotlin/kopy/compiler/fir/checker/FirKopyCheckerExtension.kt
  kopy-compiler/main/kotlin/com/javiersc/kotlin/kopy/compiler/fir/checker/FirKopyError.kt
  kopy-compiler/main/kotlin/com/javiersc/kotlin/kopy/compiler/fir/checker/checkers/FirKopyExpressionCheckers.kt
  kopy-compiler/main/kotlin/com/javiersc/kotlin/kopy/compiler/fir/checker/checkers/expression/ArgumentTypeMismatchTypeChecker.kt
  kopy-compiler/main/kotlin/com/javiersc/kotlin/kopy/compiler/fir/checker/checkers/expression/BreakingCallsChecker.kt
  kopy-compiler/main/kotlin/com/javiersc/kotlin/kopy/compiler/fir/utils/isKopyFunctionSetOrUpdateOrUpdateEach.kt
  kopy-compiler/test-data/diagnostics/type-error/type-error.fir.txt
  kopy-compiler/test-data/diagnostics/type-error/type-error.kt
  kopy-compiler/test-gen/java/com/javiersc/kotlin/kopy/compiler/DiagnosticTestGenerated.java
Labels: bug

#35 Fix errors in Kopy example
  README.md
Labels: documentation

#36 Fix Kotlin Multiplatform support
  CHANGELOG.md
  kopy-args/build.gradle.kts
  kopy-args/common/main/kotlin/com/javiersc/kotlin/kopy/args/KopyArgument.kt
  kopy-args/js/main/kotlin/com/javiersc/kotlin/kopy/args/KopyArgument.js.kt
  kopy-args/jvm/main/kotlin/com/javiersc/kotlin/kopy/args/KopyArgument.jvm.kt
  kopy-args/main/kotlin/com/javiersc/kotlin/kopy/args/KopyFunctions.kt
  kopy-args/main/kotlin/com/javiersc/kotlin/kopy/args/KopyVisibility.kt
  kopy-args/native/main/kotlin/com/javiersc/kotlin/kopy/args/KopyArgument.native.kt
  kopy-args/test/kotlin/com/javiersc/kotlin/kopy/args/KopyFunctionsTest.kt
  kopy-args/test/kotlin/com/javiersc/kotlin/kopy/args/KopyVisibilityTest.kt
  kopy-args/wasmJs/main/kotlin/com/javiersc/kotlin/kopy/args/KopyArgument.wasmJs.kt
  kopy-compiler/main/kotlin/com/javiersc/kotlin/kopy/compiler/KopyCommandLineProcessor.kt
  kopy-compiler/main/kotlin/com/javiersc/kotlin/kopy/compiler/KopyKey.kt
  kopy-compiler/main/kotlin/com/javiersc/kotlin/kopy/compiler/fir/checker/checkers/FirKopyDeclarationCheckers.kt
  kopy-compiler/main/kotlin/com/javiersc/kotlin/kopy/compiler/fir/generation/FirKopyAssignExpressionAltererExtension.kt
  kopy-compiler/main/kotlin/com/javiersc/kotlin/kopy/compiler/fir/generation/FirKopyDeclarationGenerationExtension.kt
  kopy-compiler/main/kotlin/com/javiersc/kotlin/kopy/compiler/fir/utils/isKopyFunctionSetOrUpdateOrUpdateEach.kt
  kopy-compiler/main/kotlin/com/javiersc/kotlin/kopy/compiler/ir/transformers/IrAtomicPropertyTransformer.kt
  kopy-compiler/main/kotlin/com/javiersc/kotlin/kopy/compiler/ir/transformers/IrFunctionsTransformer.kt
  kopy-compiler/main/kotlin/com/javiersc/kotlin/kopy/compiler/ir/transformers/IrSetOrUpdateCallTransformer.kt
  kopy-compiler/main/kotlin/com/javiersc/kotlin/kopy/compiler/ir/transformers/IrUpdateEachCallTransformer.kt
  kopy-compiler/main/kotlin/com/javiersc/kotlin/kopy/compiler/ir/utils/annotations.kt
  kopy-compiler/main/kotlin/com/javiersc/kotlin/kopy/compiler/ir/utils/isKopy.kt
  kopy-compiler/main/kotlin/com/javiersc/kotlin/kopy/compiler/utils/callableId.kt
  kopy-compiler/main/kotlin/com/javiersc/kotlin/kopy/compiler/utils/classId.kt
  kopy-compiler/main/kotlin/com/javiersc/kotlin/kopy/compiler/utils/fqName.kt
  kopy-compiler/main/kotlin/com/javiersc/kotlin/kopy/compiler/utils/name.kt
  kopy-compiler/main/kotlin/com/javiersc/kotlin/kopy/compiler/values.kt
  kopy-compiler/test/kotlin/com/javiersc/kotlin/kopy/compiler/GenerateKotlinCompilerTests.kt
  kopy-compiler/test/kotlin/com/javiersc/kotlin/kopy/compiler/KopyCommandLineProcessorTest.kt
Labels: bug
